name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        npm run build
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build